// Autogenerated from Pigeon (v2.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}



@interface Md5FileChecksumApiCodecReader : FlutterStandardReader
@end
@implementation Md5FileChecksumApiCodecReader
@end

@interface Md5FileChecksumApiCodecWriter : FlutterStandardWriter
@end
@implementation Md5FileChecksumApiCodecWriter
@end

@interface Md5FileChecksumApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation Md5FileChecksumApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[Md5FileChecksumApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[Md5FileChecksumApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *Md5FileChecksumApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    Md5FileChecksumApiCodecReaderWriter *readerWriter = [[Md5FileChecksumApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void Md5FileChecksumApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<Md5FileChecksumApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.Md5FileChecksumApi.getFileChecksum"
        binaryMessenger:binaryMessenger
        codec:Md5FileChecksumApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getFileChecksumFilePath:completion:)], @"Md5FileChecksumApi api (%@) doesn't respond to @selector(getFileChecksumFilePath:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_filePath = GetNullableObjectAtIndex(args, 0);
        [api getFileChecksumFilePath:arg_filePath completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
