// Autogenerated from Pigeon (v1.0.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}


@interface Md5FileChecksumApiCodecReader : FlutterStandardReader
@end
@implementation Md5FileChecksumApiCodecReader
@end

@interface Md5FileChecksumApiCodecWriter : FlutterStandardWriter
@end
@implementation Md5FileChecksumApiCodecWriter
@end

@interface Md5FileChecksumApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation Md5FileChecksumApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[Md5FileChecksumApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[Md5FileChecksumApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *Md5FileChecksumApiGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    Md5FileChecksumApiCodecReaderWriter *readerWriter = [[Md5FileChecksumApiCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void Md5FileChecksumApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<Md5FileChecksumApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Md5FileChecksumApi.getFileChecksum"
        binaryMessenger:binaryMessenger
        codec:Md5FileChecksumApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getFileChecksumFilePath:error:)], @"Md5FileChecksumApi api (%@) doesn't respond to @selector(getFileChecksumFilePath:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_filePath = args[0];
        FlutterError *error;
        NSString *output = [api getFileChecksumFilePath:arg_filePath error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
