// Autogenerated from Pigeon (v25.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetPigeonCodec(void);

@protocol Md5FileChecksumApi
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getFileChecksumFilePath:(NSString *)filePath error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpMd5FileChecksumApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<Md5FileChecksumApi> *_Nullable api);

extern void SetUpMd5FileChecksumApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<Md5FileChecksumApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
