// Autogenerated from Pigeon (v2.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by Md5FileChecksumApi.
NSObject<FlutterMessageCodec> *Md5FileChecksumApiGetCodec(void);

@protocol Md5FileChecksumApi
- (void)getFileChecksumFilePath:(NSString *)filePath completion:(void(^)(NSString *_Nullable, FlutterError *_Nullable))completion;
@end

extern void Md5FileChecksumApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<Md5FileChecksumApi> *_Nullable api);

NS_ASSUME_NONNULL_END
